import { type WeatherCondition } from '../models/weather.model';

export const WEATHER_SVG_MAP: WeatherCondition[] = [
  {
    code: 0,
    day: 'clear-day.svg',
    night: 'clear-night.svg',
    title: 'Clear sky',
  },
  {
    code: 1,
    day: 'partly-cloudy-day.svg',
    night: 'partly-cloudy-night.svg',
    title: 'Mainly clear',
  },
  {
    code: 2,
    day: 'partly-cloudy-day.svg',
    night: 'partly-cloudy-night.svg',
    title: 'Partly cloudy',
  },
  {
    code: 3,
    day: 'overcast-day.svg',
    night: 'overcast-night.svg',
    title: 'Overcast',
  },
  { code: 45, day: 'fog-day.svg', night: 'fog-night.svg', title: 'Fog' },
  { code: 48, day: 'fog-day.svg', night: 'fog-night.svg', title: 'Rime fog' },
  {
    code: 51,
    day: 'drizzle.svg',
    night: 'drizzle.svg',
    title: 'Light drizzle',
  },
  {
    code: 53,
    day: 'drizzle.svg',
    night: 'drizzle.svg',
    title: 'Moderate drizzle',
  },
  {
    code: 55,
    day: 'drizzle.svg',
    night: 'drizzle.svg',
    title: 'Dense drizzle',
  },
  {
    code: 56,
    day: 'drizzle.svg',
    night: 'drizzle.svg',
    title: 'Freezing light drizzle',
  },
  {
    code: 57,
    day: 'drizzle.svg',
    night: 'drizzle.svg',
    title: 'Freezing dense drizzle',
  },
  {
    code: 61,
    day: 'rain.svg',
    night: 'rain.svg',
    title: 'Light rain',
  },
  {
    code: 63,
    day: 'rain.svg',
    night: 'rain.svg',
    title: 'Moderate rain',
  },
  {
    code: 65,
    day: 'rain.svg',
    night: 'rain.svg',
    title: 'Heavy rain',
  },
  {
    code: 66,
    day: 'rain.svg',
    night: 'rain.svg',
    title: 'Freezing light rain',
  },
  {
    code: 67,
    day: 'rain.svg',
    night: 'rain.svg',
    title: 'Freezing heavy rain',
  },
  {
    code: 71,
    day: 'snow.svg',
    night: 'snow.svg',
    title: 'Light snow fall',
  },
  {
    code: 73,
    day: 'snow.svg',
    night: 'snow.svg',
    title: 'Moderate snow fall',
  },
  {
    code: 75,
    day: 'snow.svg',
    night: 'snow.svg',
    title: 'Heavy snow fall',
  },
  {
    code: 77,
    day: 'snow.svg',
    night: 'snow.svg',
    title: 'Snow grains',
  },
  {
    code: 80,
    day: 'rain.svg',
    night: 'rain.svg',
    title: 'Light rain showers',
  },
  {
    code: 81,
    day: 'rain.svg',
    night: 'rain.svg',
    title: 'Moderate rain showers',
  },
  {
    code: 82,
    day: 'rain.svg',
    night: 'rain.svg',
    title: 'Violent rain showers',
  },
  {
    code: 85,
    day: 'snow.svg',
    night: 'snow.svg',
    title: 'Light snow showers',
  },
  {
    code: 86,
    day: 'snow.svg',
    night: 'snow.svg',
    title: 'Heavy snow showers',
  },
  {
    code: 95,
    day: 'thunderstorms-day-rain.svg',
    night: 'thunderstorms-night-rain.svg',
    title: 'Light or moderate thunderstorm',
  },
  {
    code: 96,
    day: 'thunderstorms-day-rain.svg',
    night: 'thunderstorms-night-rain.svg',
    title: 'Thunderstorm with slight hail',
  },
  {
    code: 99,
    day: 'thunderstorms-day-rain.svg',
    night: 'thunderstorms-night-rain.svg',
    title: 'Thunderstorm with moderate hail',
  },
];
